<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\database\migrations\*.sql"
                      Link="Migrations\%(Filename)%(Extension)"
                      LogicalName="Migrations.%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
